ehosting/config/routes.rb
Rails.application.routes.draw do
    
  get 'register/index'

  get 'register/list_check_in' 
    
  post 'register/check_in'

  post 'register/list_result'  

  get 'home_page/login'
	
  get 'home_page/index'
  
  post 'home_page/verify'
    
  resources :check_ins
    
  resources :admins

  resources :guests

  resources :hosts

  root 'home_page#login'

end

ehosting/app/models/host.rb
class Host < ActiveRecord::Base
	has_many  :guests
end

ehosting/app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:name, :room, :email, :phone)
    end
end

ehosting/app/helpers/hosts_helper.rb
module HostsHelper
end

ehosting/app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :room %><br>
    <%= f.number_field :room %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ehosting/app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

ehosting/app/views/hosts/index.html.erb
<h1>Listing hosts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Room</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.name %></td>
        <td><%= host.room %></td>
        <td><%= host.email %></td>
        <td><%= host.phone %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host', new_host_path %>

ehosting/app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

ehosting/app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @host.name %>
</p>

<p>
  <strong>Room:</strong>
  <%= @host.room %>
</p>

<p>
  <strong>Email:</strong>
  <%= @host.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @host.phone %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>