ehosting/config/routes.rb
Rails.application.routes.draw do
    
  get 'register/index'

  get 'register/list_check_in' 
    
  post 'register/check_in'

  post 'register/list_result'  

  get 'home_page/login'
	
  get 'home_page/index'
  
  post 'home_page/verify'
    
  resources :check_ins
    
  resources :admins

  resources :guests

  resources :hosts

  root 'home_page#login'

end

ehosting/app/models/check_in.rb
class CheckIn < ActiveRecord::Base
    belongs_to  :host
    belongs_to  :guest
end

ehosting/app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :set_check_in, only: [:show, :edit, :update, :destroy]

  # GET /check_ins
  # GET /check_ins.json
  def index
    @check_ins = CheckIn.all
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = CheckIn.new
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins
  # POST /check_ins.json
  def create
    @check_in = CheckIn.new(check_in_params)

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to @check_in, notice: 'Check in was successfully created.' }
        format.json { render :show, status: :created, location: @check_in }
      else
        format.html { render :new }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1
  # PATCH/PUT /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to @check_in, notice: 'Check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_in }
      else
        format.html { render :edit }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.json
  def destroy
    @check_in.destroy
    respond_to do |format|
      format.html { redirect_to check_ins_url, notice: 'Check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = CheckIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_params
      params.require(:check_in).permit(:host_id, :guest_id, :date_in, :date_out)
    end
end

ehosting/app/helpers/check_ins_helper.rb
module CheckInsHelper
end

ehosting/app/views/check_ins/_form.html.erb
<%= form_for(@check_in) do |f| %>
  <% if @check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% @check_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host_id %><br>
    <%= f.number_field :host_id %>
  </div>
  <div class="field">
    <%= f.label :guest_id %><br>
    <%= f.number_field :guest_id %>
  </div>
  <div class="field">
    <%= f.label :date_in %><br>
    <%= f.date_select :date_in %>
  </div>
  <div class="field">
    <%= f.label :date_out %><br>
    <%= f.date_select :date_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ehosting/app/views/check_ins/edit.html.erb
<h1>Editing check_in</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_in %> |
<%= link_to 'Back', check_ins_path %>

ehosting/app/views/check_ins/index.html.erb
<h1>Listing check_ins</h1>

<table>
  <thead>
    <tr>
      <th>Host</th>
      <th>Guest</th>
      <th>Date in</th>
      <th>Date out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_ins.each do |check_in| %>
      <tr>
        <td><%= check_in.host_id %></td>
        <td><%= check_in.guest_id %></td>
        <td><%= check_in.date_in %></td>
        <td><%= check_in.date_out %></td>
        <td><%= link_to 'Show', check_in %></td>
        <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
        <td><%= link_to 'Destroy', check_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check in', new_check_in_path %>

ehosting/app/views/check_ins/new.html.erb
<h1>New check_in</h1>

<%= render 'form' %>

<%= link_to 'Back', check_ins_path %>

ehosting/app/views/check_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @check_in.host_id %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @check_in.guest_id %>
</p>

<p>
  <strong>Date in:</strong>
  <%= @check_in.date_in %>
</p>

<p>
  <strong>Date out:</strong>
  <%= @check_in.date_out %>
</p>

<%= link_to 'Edit', edit_check_in_path(@check_in) %> |
<%= link_to 'Back', check_ins_path %>