ehosting/config/routes.rb
Rails.application.routes.draw do
    
  get 'register/index'

  get 'register/list_check_in' 
    
  post 'register/check_in'

  post 'register/list_result'  

  get 'home_page/login'
	
  get 'home_page/index'
  
  post 'home_page/verify'
    
  resources :check_ins
    
  resources :admins

  resources :guests

  resources :hosts

  root 'home_page#login'

end

ehosting/app/models/guest.rb
class Guest < ActiveRecord::Base
		has_many  :hosts
end

ehosting/app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:name, :email, :phone)
    end
end

ehosting/app/helpers/guests_helper.rb
module GuestsHelper
end

ehosting/app/views/guests/_form.html.erb
<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">
        <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
        </p>
            
        <div class="jumbotron">
            <h3>New Guest</h3><br>
            
            <%= form_for(@guest) do |f| %>
            <% if @guest.errors.any? %>
            <div id="error_explanation">
            <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

            <ul>
            <% @guest.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            </div>
            <% end %>

            <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
            </div>
            <div class="field">
            <%= f.label :email %><br>
            <%= f.text_field :email %>
            </div>
            <div class="field">
            <%= f.label :phone %><br>
            <%= f.text_field :phone %>
            </div>
            <div class="actions">
            <%= f.submit "Create Guest", class: "btn btn-primary" %>
            </div>
            <% end %>
        </div>

    </div>


    <div class="col-xs-6 col-sm-2 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">
            <%= link_to 'Home Page', home_page_index_path,  class: "list-group-item" %>
            <%= link_to 'New Guest', new_guest_path,  class: "list-group-item active" %>
            <%= link_to 'New Check in', register_index_path, class: "list-group-item" %>
            <%= link_to 'Reports', register_list_check_in_path, class: "list-group-item" %>
            <%= link_to 'Logout', home_page_login_path, class: "list-group-item" %>
        </div>
    </div><!--/.sidebar-offcanvas-->
</div>

ehosting/app/views/guests/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @guest, class: "btn btn-primary", :style => "color: #fff" %> 
<%= link_to 'Back', home_page_index_path, class: "btn btn-primary", :style => "color: #fff" %>

ehosting/app/views/guests/index.html.erb
<h1>Listing guests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.email %></td>
        <td><%= guest.phone %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

ehosting/app/views/guests/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', home_page_index_path, :class => "btn btn-primary", :style => "color: #fff" %>

ehosting/app/views/guests/show.html.erb
<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">
        <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
        </p>
        <div class="jumbotron">
            <p id="notice"><%= notice %></p>

            <p>
              <strong>Name:</strong>
              <%= @guest.name %>
            </p>

            <p>
              <strong>Email:</strong>
              <%= @guest.email %>
            </p>

            <p>
              <strong>Phone:</strong>
              <%= @guest.phone %>
            </p>

        </div>

    </div>


    <div class="col-xs-6 col-sm-2 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">
            <%= link_to 'Home Page', home_page_index_path,  class: "list-group-item" %>
            <%= link_to 'New Guest', new_guest_path,  class: "list-group-item active" %>
            <%= link_to 'New Check in', register_index_path, class: "list-group-item" %>
            <%= link_to 'Reports', register_list_check_in_path, class: "list-group-item" %>
            <%= link_to 'Logout', home_page_login_path, class: "list-group-item" %>
        </div>
    </div><!--/.sidebar-offcanvas-->
</div>

<%= link_to 'Edit', edit_guest_path(@guest), class: "btn btn-primary", :style => "color: #fff" %> 
<%= link_to 'Back', home_page_index_path, class: "btn btn-primary", :style => "color: #fff" %>